site_name: DfSchema Documentation

theme:
  name: "material"
  palette:
    primary: yellow
    accent: deep orange

plugins:
  - mkdocstrings

docs_dir: "../../docs"

nav:
  - Quickstart: index.md
  - new_style.md
  - old_style.md
  - Command Line Interface: cli.md
  - tutorials.md
  - benchmarks.md
  - Roadmap and Changelog: rm_and_changelog.md
