name: Publish to Test PyPI

on:
  push:
    branches: [ main ]

jobs:

  test_and_build:
    # The type of runner that the job will run on

    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
           python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Lint with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            uv run flake8 . --count --max-line-length=127 --show-source --statistics

      - name: Run tests
        run: uv run pytest

      - name: Build
        run: uv build --wheel

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: |
            dist

  gather_n_publish:
    runs-on: ubuntu-latest
    needs: test_and_build

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
           python-version: 3.8

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Bump version
        run: uv version --bump patch

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build sdist
        run: uv build --sdist

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./

      - name: Publish package
        run: uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ secrets.TEST_PYPI_TOKEN }}

  build_docs:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    needs: test_and_build

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .config/mkdocs/mkdocs.yml
          REQUIREMENTS: .config/mkdocs/requirements.txt
          # EXTRA_PACKAGES: build-base
